'use client';
import {useState,useEffect} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
const prefectures='北海道 青森県 岩手県 宮城県 秋田県 山形県 福島県 茨城県 栃木県 群馬県 埼玉県 千葉県 東京都 神奈川県 新潟県 富山県 石川県 福井県 山梨県 長野県 岐阜県 静岡県 愛知県 三重県 滋賀県 京都府 大阪府 兵庫県 奈良県 和歌山県 鳥取県 島根県 岡山県 広島県 山口県 徳島県 香川県 愛媛県 高知県 福岡県 佐賀県 長崎県 熊本県 大分県 宮崎県 鹿児島県 沖縄県'.split(' ');
export function InfoDialog({kind}:{kind:'company'|'privacy'}){return <Dialog><DialogTrigger className="text-link">{kind==='company'?'運営会社情報':'個人情報保護方針'}</DialogTrigger><DialogContent className="info-dialog" showCloseButton={false}><DialogTitle>{kind==='company'?'運営会社情報':'個人情報の取り扱いについて'}</DialogTitle><DialogDescription>{kind==='company'?'このページはフレッツ光クロスBIZのリニューアル確認版です。正式な運営会社情報・契約主体・窓口情報は公開前に確定する必要があります。':'この確認版では、お問い合わせ内容や連絡先は送信・保存されません。郵便番号の住所検索を利用した場合は、入力した郵便番号のみをzipcloudへ送信します。正式公開時の個人情報保護方針は、運営者と送信先の確定後に掲載します。'}</DialogDescription><DialogClose className="button secondary">閉じる</DialogClose></DialogContent></Dialog>}
export function ContactForm({area=false}:{area?:boolean}){
 const [step,setStep]=useState(1),[postal,setPostal]=useState(''),[pref,setPref]=useState<string|null>(null),[city,setCity]=useState(''),[street,setStreet]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[consent,setConsent]=useState(false);
 useEffect(()=>{if(!area)return;const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'stage_area_check',title:'提供エリア確認の住所を入力',description:'確認版の住所入力に値を設定し、連絡先入力へ進みます。提供可否の判定・送信・保存はしません。',inputSchema:{type:'object',properties:{postalCode:{type:'string'},prefecture:{type:'string'},city:{type:'string'},street:{type:'string'}},required:['postalCode','prefecture','city','street'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object')throw Error('住所が必要です');const v=input as Record<string,unknown>;if(typeof v.postalCode!=='string'||!/^\d{3}-?\d{4}$/.test(v.postalCode)||typeof v.prefecture!=='string'||!prefectures.includes(v.prefecture)||typeof v.city!=='string'||!v.city.trim()||typeof v.street!=='string'||!v.street.trim())throw Error('有効な郵便番号・都道府県・市区町村・町名番地を指定してください');setPostal(v.postalCode);setPref(v.prefecture);setCity(v.city);setStreet(v.street);setStep(2);setDone(false);setNotice('');await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));document.getElementById('area-form')?.scrollIntoView({behavior:'auto'});return{status:'staged',step:2,submitted:false,availability:'not_checked'};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[area]);
 async function lookup(){const code=postal.replace(/[-ー\s]/g,''); if(!/^\d{7}$/.test(code)){setNotice('郵便番号を7桁の数字で入力してください。');return;}setBusy(true);setNotice('');try{const res=await fetch('https://zipcloud.ibsnet.co.jp/api/search?zipcode='+encodeURIComponent(code),{signal:AbortSignal.timeout(8000)});const data=await res.json() as {results?:Array<{address1:string;address2:string;address3:string}>};const hit=data.results?.[0];if(!hit)throw Error();setPref(hit.address1);setCity(hit.address2);setStreet(hit.address3);setNotice('住所を入力しました。町名・番地をご確認ください。');}catch{setNotice('住所を取得できませんでした。住所を手入力してください。');}finally{setBusy(false);}}
 return <form className="contact-form" onSubmit={e=>{e.preventDefault();if(area&&step===1){if(!pref){setNotice('都道府県を選択してください。');return;}setStep(2);setNotice('');}else{setDone(true);setNotice('入力内容を確認しました。この確認版では送信されていません。');}}}>
 {area&&<div className="form-steps"><span className={step===1?'active':''}>01 住所を入力</span><span className={step===2?'active':''}>02 連絡先を入力</span></div>}
 {area&&step===1?<><label htmlFor="area-postal">郵便番号 <i>必須</i></label><div className="postal-row"><input id="area-postal" autoComplete="postal-code" inputMode="numeric" value={postal} onChange={e=>setPostal(e.target.value)} placeholder="例：5300001" pattern="[0-9]{3}-?[0-9]{4}" required/><button type="button" onClick={lookup} disabled={busy}>{busy?'検索中…':'住所を自動入力'}</button></div><p className="input-help">住所検索にはzipcloudを利用します。</p><label id="pref-label">都道府県 <i>必須</i></label><Select value={pref} onValueChange={v=>setPref(v)}><SelectTrigger aria-labelledby="pref-label" className="pref-select"><SelectValue placeholder="選択してください"/></SelectTrigger><SelectContent>{prefectures.map(p=><SelectItem value={p} key={p}>{p}</SelectItem>)}</SelectContent></Select><label htmlFor="area-city">市区町村 <i>必須</i></label><input id="area-city" autoComplete="address-level2" value={city} onChange={e=>setCity(e.target.value)} required placeholder="例：大阪市北区"/><label htmlFor="area-street">町名・番地・建物名 <i>必須</i></label><input id="area-street" autoComplete="street-address" value={street} onChange={e=>setStreet(e.target.value)} required placeholder="例：梅田1-2-3 ○○ビル3F"/><button className="button primary" type="submit">連絡先の入力へ進む <span>→</span></button></>:<>{area&&<div className="address-summary"><b>確認する住所</b><p>〒{postal} {pref}{city}{street}</p><button type="button" onClick={()=>{setStep(1);setDone(false);setNotice('');}}>住所を修正する</button></div>}{[['company','会社名・屋号','organization','text'],['name','ご担当者名','name','text'],['tel','電話番号','tel','tel'],['email','メールアドレス','email','email']].map(([name,label,ac,type])=><div key={name}><label htmlFor={(area?'area-':'apply-')+name}>{label} <i>必須</i></label><input id={(area?'area-':'apply-')+name} name={name} type={type} autoComplete={ac} required pattern={type==='tel'?'[0-9+() -]{10,16}':undefined} onChange={()=>setDone(false)}/></div>)}<div className="consent"><Checkbox id={area?'area-consent':'apply-consent'} checked={consent} onCheckedChange={setConsent} required/><label htmlFor={area?'area-consent':'apply-consent'}>個人情報の取り扱いを確認しました</label></div><InfoDialog kind="privacy"/><button className="button primary" type="submit" disabled={!consent||done}>{done?'入力内容を確認しました':'入力内容を確認する'} <span>→</span></button></>}
 {notice&&<p role="status" className="form-notice">{notice}</p>}<p className="fine">デザイン確認版のため、入力内容は送信されません。<br/>{area?'正式な提供可否は、建物・設備状況を確認してご案内します。':'実際のご相談は、お電話をご利用ください。'}</p>
 </form>
}
